### ISSUE TITLE
Replace pip3 by pip?

### ISSUE THREAD

**Issue by deoxyribose** [Bystroushaak/meaningness.com_epub_generator#1]
Hi, thanks for writing this! Just a small detail: when installing the requirements with `pip3 install --user -r requirements.txt`, my python environment couldn't find dhtmlparser, but installing with just pip worked fine.

**Comment by Bystroushaak** [comment]
Thanks for the report.

**Comment by Bystroushaak** [comment]
Can you give me more details about your environment? I couldn't replicate this.

**Comment by Bystroushaak** [comment]
I am not sure about the replacing `pip3` with `pip`, because on most of the (older) linux environments, `pip` is used to install `python2` packages and `pip3` installs `python3` packages. That said, on the newest ubuntu, `pip` is actually configured for `python3`;

```
pip -V
pip 20.3.3 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

I'll update the readme to mention this.
